version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports: [ "1883:1883" ]
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: [ "5432:5432" ]
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./src/backend
    container_name: backend
    env_file: [.env]
    depends_on: [ db, mqtt ]
    ports: [ "8000:8000" ]

  simulator:
    build: ./src/simulator
    container_name: simulator
    env_file: [.env]
    depends_on: [ mqtt ]
    command: ["python", "simulate.py"]

  dashboard:
    build: ./src/dashboard
    container_name: dashboard
    env_file: [.env]
    depends_on: [ backend ]
    ports: [ "8501:8501" ]

volumes:
  db-data: 